# Generated by Django 3.1.1 on 2020-09-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'watched asset',
                'verbose_name_plural': 'watched assets',
                'unique_together': {('asset', 'user')},
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='watch_list',
            field=models.ManyToManyField(blank=True, through='users.WatchedAsset', to='assets.Asset'),
        ),
    ]
