# Generated by Django 3.1.1 on 2020-09-21 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('mic', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'exchange',
                'verbose_name_plural': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.exchange')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high', models.DecimalField(decimal_places=2, max_digits=9)),
                ('low', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.IntegerField()),
                ('adj_open', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('adj_high', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('adj_low', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('adj_volume', models.IntegerField(null=True)),
                ('ema', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('macd', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('rsi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assets.asset')),
            ],
            options={
                'verbose_name': 'daily report',
                'verbose_name_plural': 'daily reports',
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
