# Generated by Django 3.1.1 on 2020-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
