# Generated by Django 3.1.1 on 2020-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_report_macd'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='macd',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
