# Generated by Django 3.1.1 on 2020-09-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200919_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': 'daily report', 'verbose_name_plural': 'daily reports'},
        ),
    ]
