# Generated by Django 3.1.1 on 2020-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200921_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
