# Generated by Django 3.1.1 on 2020-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='adj_close',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='adj_high',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='adj_low',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='adj_open',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='adj_volume',
            field=models.IntegerField(null=True),
        ),
    ]
