# Generated by Django 3.1.1 on 2020-09-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_report_macd'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='macd_hist',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='macd_signal',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
