# Generated by Django 3.1.1 on 2020-09-19 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
            },
        ),
    ]
