# Generated by Django 3.1.1 on 2020-09-19 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='ticker',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last',
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=9)),
                ('high', models.DecimalField(decimal_places=2, max_digits=9)),
                ('low', models.DecimalField(decimal_places=2, max_digits=9)),
                ('close', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume', models.IntegerField()),
                ('adj_open', models.DecimalField(decimal_places=2, max_digits=9)),
                ('adj_high', models.DecimalField(decimal_places=2, max_digits=9)),
                ('adj_low', models.DecimalField(decimal_places=2, max_digits=9)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=9)),
                ('adj_volume', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assets.asset')),
            ],
        ),
    ]
