# Generated by Django 3.1.1 on 2020-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200919_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='ema',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='macd',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='rsi',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
